Disable Windows jobs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -55,29 +55,32 @@ jobs:
         name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}
         path: luac.cross
 
+# The files in the 'msvc' folder would need to be updated to be compatible with VS 2022.
+# Sample job (that failed): https://github.com/nodemcu/nodemcu-firmware/actions/runs/17306868602/job/49131917376#step:3:153
+# => disable the Windows jobs for now
 
-  build_luac_cross_win:
+  # build_luac_cross_win:
 
-    runs-on: windows-2019
+  #   runs-on: windows-2022
 
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        submodules: true
-    - name: Build luac.cross.exe
-      run: |
-        set
-        "%programfiles%\git\usr\bin\xargs"
-        cd msvc
-        "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release /p:Platform=x64
-        mv luac-cross/x64/Release/luac.cross.exe ..
-      shell: cmd
-    - name: Upload luac.cross
-      if: ${{ success() }}
-      uses: actions/upload-artifact@v4
-      with:
-        name: luac.cross_51_float_win
-        path: luac.cross.exe
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #     with:
+  #       submodules: true
+  #   - name: Build luac.cross.exe
+  #     run: |
+  #       set
+  #       "C:\msys64\usr\bin\xargs.exe"
+  #       cd msvc
+  #       "%programfiles%\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release /p:Platform=x64
+  #       mv luac-cross/x64/Release/luac.cross.exe ..
+  #     shell: cmd
+  #   - name: Upload luac.cross
+  #     if: ${{ success() }}
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: luac.cross_51_float_win
+  #       path: luac.cross.exe
 
 
   compile_lua:
@@ -117,33 +120,33 @@ jobs:
       shell: bash
 
 
-  compile_lua_win:
+  # compile_lua_win:
 
-    strategy:
-      fail-fast: false
-      matrix:
-        lua_ver: [51]
-        numbers: ['float']
-        filter: [ 'cat' ]
-    needs: build_luac_cross_win
-    runs-on: windows-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       lua_ver: [51]
+  #       numbers: ['float']
+  #       filter: [ 'cat' ]
+  #   needs: build_luac_cross_win
+  #   runs-on: windows-latest
 
-    steps:
-    - name: Checkout repo
-      uses: actions/checkout@v4
-      with:
-        submodules: false
-    - name: Download luac.cross
-      uses: actions/download-artifact@v4
-      with:
-        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
-        path: ./
-    - name: compile Lua
-      run: |
-        PATH="/C/Program\ Files/Git/usr/bin:${PATH}"
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" echo
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" ./luac.cross -p
-      shell: bash
+  #   steps:
+  #   - name: Checkout repo
+  #     uses: actions/checkout@v4
+  #     with:
+  #       submodules: false
+  #   - name: Download luac.cross
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
+  #       path: ./
+  #   - name: compile Lua
+  #     run: |
+  #       PATH="/C/Program\ Files/Git/usr/bin:${PATH}"
+  #       find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" echo
+  #       find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" ./luac.cross -p
+  #     shell: bash
 
 
   NTest:
@@ -188,39 +191,39 @@ jobs:
       shell: bash
 
 
-  NTest_win:
+  # NTest_win:
 
-    strategy:
-      fail-fast: false
-      matrix:
-        lua_ver: [51]
-        numbers: ['float']
-    needs: build_luac_cross_win
-    runs-on: windows-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       lua_ver: [51]
+  #       numbers: ['float']
+  #   needs: build_luac_cross_win
+  #   runs-on: windows-latest
 
-    steps:
-    - name: Checkout repo
-      uses: actions/checkout@v4
-      with:
-        submodules: false
-    - name: Download luac.cross
-      uses: actions/download-artifact@v4
-      with:
-        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
-        path: ./
-    - name: NTest selfcheck
-      run: |
-        cd tests/NTest
-        ../../luac.cross.exe -e ../NTest/NTest_NTest.lua | tee log
-        grep "failed. 0" log
-      shell: bash
-    - name: NTest hosttests
-      run: |
-        cd tests
-        cp NTest/NTest.lua .
-        ../luac.cross.exe -e NTest_lua.lua | tee log
-        (if grep  " ==>  " log ; then exit 1 ; fi)
-      shell: bash
+  #   steps:
+  #   - name: Checkout repo
+  #     uses: actions/checkout@v4
+  #     with:
+  #       submodules: false
+  #   - name: Download luac.cross
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
+  #       path: ./
+  #   - name: NTest selfcheck
+  #     run: |
+  #       cd tests/NTest
+  #       ../../luac.cross.exe -e ../NTest/NTest_NTest.lua | tee log
+  #       grep "failed. 0" log
+  #     shell: bash
+  #   - name: NTest hosttests
+  #     run: |
+  #       cd tests
+  #       cp NTest/NTest.lua .
+  #       ../luac.cross.exe -e NTest_lua.lua | tee log
+  #       (if grep  " ==>  " log ; then exit 1 ; fi)
+  #     shell: bash
 
 
   luacheck:
